import 'save_state.dart';

typedef Entity = int;
abstract interface class StoryPort { List<Map<String, dynamic>> get events; List<Map<String, dynamic>> get endings; List<Map<String, dynamic>> get personalities; List<Map<String, dynamic>> get companions; List<Map<String, dynamic>> get milestones; int get endingWeek; }
abstract interface class SavePort { void write(String value); String? read(); void clear(); }
class JsonStoryAdapter implements StoryPort { JsonStoryAdapter(this.source); final Map<String, dynamic> source; @override List<Map<String, dynamic>> get events => (source['events'] as List? ?? []).cast<Map<String, dynamic>>(); @override List<Map<String, dynamic>> get endings => (source['endings'] as List? ?? []).cast<Map<String, dynamic>>(); @override List<Map<String, dynamic>> get personalities => (source['personalities'] as List? ?? []).cast<Map<String, dynamic>>(); @override List<Map<String, dynamic>> get companions => (source['companions'] as List? ?? []).cast<Map<String, dynamic>>(); @override List<Map<String, dynamic>> get milestones => (source['milestones'] as List? ?? []).cast<Map<String, dynamic>>(); @override int get endingWeek => source['endingWeek'] as int? ?? 12; }
class MemorySaveAdapter implements SavePort { String? value; @override void write(String value) => this.value = value; @override String? read() => value; @override void clear() => value = null; }
Map<String, dynamic> resolveEnding(StoryPort story, Map<String, int> stats, {Map<String, int>? bonds, Map<String, bool>? milestones}) { final winner = stats.entries.reduce((a, b) => a.value > b.value ? a : b); final options = story.endings.where((e) => e['stat'] == winner.key).toList()..sort((a, b) => ((b['min'] as int?) ?? 0).compareTo((a['min'] as int?) ?? 0)); final eligible = options.where((e) => winner.value >= ((e['min'] as int?) ?? 0) && ((e['requiresMilestones'] as List?) ?? const []).every((id) => milestones?[id] == true)).toList(); final result = Map<String, dynamic>.from(options.isEmpty ? {'id': 'unwritten', 'title': '루멘의 다음 장', 'body': '아직 이름 붙지 않은 가능성이 남아 있다.', 'stat': winner.key} : eligible.isEmpty ? options.last : eligible.first); if (bonds != null) { Map<String, dynamic>? chosen; for (final c in story.companions) { if ((bonds[c['id']] ?? 0) >= ((c['bondThreshold'] as int?) ?? 8) && (chosen == null || (bonds[c['id']] ?? 0) > (bonds[chosen['id']] ?? 0))) chosen = c; } if (chosen != null) result['epilogue'] = chosen['epilogue']; } return result; }

sealed class GameEvent { const GameEvent(); }
class ActivityChosen extends GameEvent { const ActivityChosen(this.stat, this.delta, this.coins, this.fatigue, {this.label = '', this.bonus = 0}); final String stat, label; final int delta, coins, fatigue, bonus; }
class StoryChoiceMade extends GameEvent { const StoryChoiceMade(this.stat, this.delta, this.coins, this.label, {this.bondId, this.bondDelta = 0, this.requiresStat, this.requiresMin = 0, this.line = ''}); final String stat, label, line; final int delta, coins, bondDelta, requiresMin; final String? bondId, requiresStat; }
class WeekAdvanced extends GameEvent { const WeekAdvanced(); }
class MilestoneResolved extends GameEvent { const MilestoneResolved(this.id, this.title, this.stat, this.min, this.coins, this.pass, this.fail); final String id, title, stat, pass, fail; final int min, coins; }

class StatsComponent { StatsComponent(this.values); final Map<String, int> values; }
class ProgressComponent { int week = 1; int coins = 12; int fatigue = 0; int selected = 0; int persona = 0; int eventIndex = 0; String lastResult = '', lastLine = ''; final bonds = <String, int>{'lumi':0,'bora':0,'taro':0}; final milestones = <String, bool>{}; final trace = <String>[]; }

/// DOD/ECS core: components are data, systems consume ordered events.
class GameWorld {
  GameWorld() { stats[0] = StatsComponent({'지혜': 4, '공감': 5, '용기': 3}); progress[0] = ProgressComponent(); }
  final stats = <Entity, StatsComponent>{};
  final progress = <Entity, ProgressComponent>{};
  final _queue = <GameEvent>[];
  void dispatch(GameEvent event) { _queue.add(event); while (_queue.isNotEmpty) _system(_queue.removeAt(0)); progress[0]!.coins = progress[0]!.coins.clamp(0, 999).toInt(); }
  void _system(GameEvent e) { final s = stats[0]!.values, p = progress[0]!; switch (e) { case ActivityChosen(:final stat, :final delta, :final coins, :final fatigue, :final label, :final bonus): final raw = delta + bonus, growth = (p.fatigue >= 8 ? (raw - 1).clamp(0, raw) : raw).toInt(); s[stat] = s[stat]! + growth; p.coins += coins; p.fatigue = (p.fatigue + fatigue).clamp(0, 12).toInt(); p.lastResult = '${label.isEmpty ? stat : label} · $stat +$growth · 피로 ${fatigue >= 0 ? '+' : ''}$fatigue${bonus == 0 ? '' : ' · 성격 재능 +$bonus'}'; p.lastLine = ''; p.trace.add('activity:$stat+$growth${bonus == 0 ? '' : '|talent+$bonus'}'); case StoryChoiceMade(:final stat, :final delta, :final coins, :final label, :final bondId, :final bondDelta, :final line): s[stat] = s[stat]! + delta; p.coins += coins; if (bondId != null) p.bonds[bondId] = ((p.bonds[bondId] ?? 0) + bondDelta).clamp(0, 100).toInt(); p.lastResult = '$label · $stat +$delta${bondId == null ? '' : ' · $bondId 유대 +$bondDelta'}'; p.lastLine = line; p.trace.add('event:$label${bondId == null ? '' : '|bond:$bondId+$bondDelta'}${line.isEmpty ? '' : '|line:$line'}'); case WeekAdvanced(): p.week++; case MilestoneResolved(:final id, :final title, :final stat, :final min, :final coins, :final pass, :final fail): final success = (s[stat] ?? 0) >= min; p.milestones[id] = success; if (success) p.coins += coins; p.lastResult = '$title · ${success ? pass : fail}${success ? ' · 은화 +$coins' : ''}'; p.lastLine = ''; p.trace.add('milestone:$id:${success ? 'pass' : 'fail'}'); } }
  GameSnapshot snapshot({int page = 0}) { final p = progress[0]!; return GameSnapshot(week: p.week, coins: p.coins, fatigue: p.fatigue, selected: p.selected, persona: p.persona, page: page, eventIndex: p.eventIndex, stats: Map.of(stats[0]!.values), bonds: Map.of(p.bonds), milestones: Map.of(p.milestones), lastResult: p.lastResult, lastLine: p.lastLine, history: List.of(p.trace)); }
  void restore(GameSnapshot s) { final p = progress[0]!; p.week=s.week; p.coins=s.coins; p.fatigue=s.fatigue; p.selected=s.selected; p.persona=s.persona; p.eventIndex=s.eventIndex; p.lastResult=s.lastResult; p.lastLine=s.lastLine; p.bonds..clear()..addAll(s.bonds); p.milestones..clear()..addAll(s.milestones); p.trace..clear()..addAll(s.history); stats[0]!.values..clear()..addAll(s.stats); }
}

/// Application port: UI sends commands; adapters handle story and saves.
class GameSession {
  GameSession(this.story, this.save);
  final StoryPort story; final SavePort save; final world = GameWorld();
  void choose(ActivityChosen e) { final p = world.progress[0]!; if (p.week >= story.endingWeek) { p.lastResult = '${story.endingWeek}주 기록이 완성되었습니다 · 새 기록을 시작하세요.'; persist(); return; } final people = story.personalities, person = people.isEmpty ? null : people[p.persona.clamp(0, people.length - 1)]; final bonus = e.delta > 0 && person?['focusStat'] == e.stat ? (person?['focusBonus'] as int? ?? 0) : 0; world.dispatch(ActivityChosen(e.stat, e.delta, e.coins, e.fatigue, label: e.label, bonus: bonus)); world.dispatch(const WeekAdvanced()); if (!story.events.any((e) => e['week'] == world.progress[0]!.week)) _resolveMilestone(); persist(); }
  void chooseEvent(StoryChoiceMade e) { final p = world.progress[0]!; if (p.week >= story.endingWeek) { p.lastResult = '${story.endingWeek}주 기록이 완성되었습니다 · 새 기록을 시작하세요.'; persist(); return; } if (e.requiresStat != null && (world.stats[0]!.values[e.requiresStat] ?? 0) < e.requiresMin) { p.lastResult = '조건 부족 · ${e.requiresStat} $e.requiresMin 필요'; persist(); return; } world.dispatch(e); _resolveMilestone(); persist(); }
  void _resolveMilestone() { final m = story.milestones.where((m) => m['week'] == world.progress[0]!.week && !world.progress[0]!.milestones.containsKey(m['id'])).firstOrNull; if (m != null) world.dispatch(MilestoneResolved(m['id'], m['title'], m['stat'], m['min'], m['coins'], m['pass'], m['fail'])); }
  void persist({int page = 0}) => save.write(world.snapshot(page: page).encode());
  GameSnapshot? restore() { final raw = save.read(); if (raw == null) return null; final snapshot = GameSnapshot.decode(raw); world.restore(snapshot); return snapshot; }
  GameSnapshot snapshot({int page = 0}) => world.snapshot(page: page);
}
