import 'dart:convert';
import 'dart:math';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'design_tokens.dart';
import 'feedback_banner.dart';
import 'i18n.dart';
import 'save_state.dart';
import 'save_adapter.dart';
import 'collection_adapter.dart';
import 'collection_platform.dart';
import 'game_core.dart';
typedef Activity=({String label,String icon,String hint,String stat,int delta,int fatigue,int coins});
const defaultActivities=<Activity>[(label:'별 관측',icon:'✦',hint:'지혜 +3 · 피로 +1',stat:'지혜',delta:3,fatigue:1,coins:0),(label:'정원 돌보기',icon:'❈',hint:'공감 +3 · 피로 +1',stat:'공감',delta:3,fatigue:1,coins:0),(label:'공방 돕기',icon:'◈',hint:'용기 +2 · 은화 +4',stat:'용기',delta:2,fatigue:1,coins:4),(label:'달빛 아래 휴식',icon:'☾',hint:'피로 -2 · 성장 없음',stat:'지혜',delta:0,fatigue:-2,coins:0),(label:'장터 심부름',icon:'◇',hint:'은화 +6 · 피로 +1',stat:'공감',delta:0,fatigue:1,coins:6)];
Future<void> main()async{WidgetsFlutterBinding.ensureInitialized();final s=jsonDecode(await rootBundle.loadString('story/story.json'));final locales=<String,Map<String,String>>{};for(final locale in ['ko','en']){final raw=jsonDecode(await rootBundle.loadString('story/locales/$locale.json')) as Map;locales[locale]=raw.map((key,value)=>MapEntry('$key','$value'));}runApp(Game(s,locales:locales));}
class Game extends StatefulWidget{const Game(this.story,{this.locales=const {},super.key});final Map<String,dynamic>story;final Map<String,Map<String,String>>locales;@override State<Game> createState()=>_Game();}
class _Game extends State<Game>{int week=1,coins=12,fatigue=0,selected=0,page=0,persona=0,eventIndex=0;String locale='ko';bool finished=false;final history=<String>[];final stats={'지혜':4,'공감':5,'용기':3},bonds={'lumi':0,'bora':0,'taro':0};final milestones=<String,bool>{};final collectionEntries=<Map<String,dynamic>>[];String lastResult='',lastLine='';ui.Image? image,personaImage;late GameSession session;late CollectionPort collection;
LocaleCatalog get catalog=>LocaleCatalog(widget.locales);
String tr(String key,String fallback)=>catalog.text(locale,key,fallback:fallback);
void toggleLocale()=>setState((){locale=locale=='ko'?'en':'ko';setActiveLocale(locale,catalog);});
List<Activity> get activities {final raw=widget.story['activities'] as List?;if(raw==null||raw.isEmpty)return defaultActivities;return raw.map((e){final a=e as Map;return(label:'${a['label']}',icon:'${a['icon']}',hint:'${a['hint']}',stat:'${a['stat']}',delta:(a['delta'] as int?)??0,fatigue:(a['fatigue'] as int?)??0,coins:(a['coins'] as int?)??0);}).toList();}
@override void initState(){super.initState();collection=createCollectionAdapter();collectionEntries.addAll(collection.read());session=GameSession(JsonStoryAdapter(widget.story),createSaveAdapter());try{final restored=session.restore();if(restored!=null)page=restored.page;}catch(_){ }sync();FontLoader('NotoSansKR')..addFont(rootBundle.load('assets/fonts/NotoSansKR-Regular.ttf'))..load().then((_){if(mounted)setState((){});});rootBundle.load('assets/noa-sprite-sheet.png').then((b)=>ui.instantiateImageCodec(b.buffer.asUint8List())).then((c)=>c.getNextFrame()).then((f){if(mounted)setState(()=>image=f.image);});rootBundle.load('assets/lumen-personality-sheet.png').then((b)=>ui.instantiateImageCodec(b.buffer.asUint8List())).then((c)=>c.getNextFrame()).then((f){if(mounted)setState(()=>personaImage=f.image);});}
void sync(){setActiveLocale(locale,catalog);final s=session.snapshot(page:page);week=s.week;coins=s.coins;fatigue=s.fatigue;selected=s.selected;persona=s.persona;eventIndex=s.eventIndex;lastResult=s.lastResult;lastLine=s.lastLine;history..clear()..addAll(s.history);stats..clear()..addAll(s.stats);bonds..clear()..addAll(s.bonds);milestones..clear()..addAll(s.milestones);}
void next(){final a=activities[selected.clamp(0,activities.length-1)];setState((){session.choose(ActivityChosen(a.stat,a.delta,a.coins,a.fatigue,label:a.label));sync();if(week>=session.story.endingWeek){finished=true;recordEnding();page=2;}else{final upcoming=session.story.events.indexWhere((e)=>e['week']==week);if(upcoming>=0){eventIndex=upcoming;session.world.progress[0]!.eventIndex=eventIndex;page=3;}}session.persist(page:page);});}
void recordEnding(){final d=resolveEnding(JsonStoryAdapter(widget.story),stats,bonds:bonds,milestones:milestones);collection.record('${d['id']}',(d['rank'] as int?)??1);collectionEntries..clear()..addAll(collection.read());}
bool choiceAvailable(Map e)=>e['requiresStat']==null||(stats[e['requiresStat']]??0)>=(e['requiresMin'] as int? ?? 0);
void chooseEvent(int i){final e=session.story.events[eventIndex]['choices'][i];if(!choiceAvailable(e)){setState(()=>lastResult='조건 부족 · ${e['requiresStat']} ${e['requiresMin']} 필요');return;}final d=e['delta'] as int,g=e['coins'] as int;setState((){session.chooseEvent(StoryChoiceMade(e['stat'],d,g,e['label'],bondId:e['bondId'] as String?,bondDelta:(e['bondDelta'] as int?)??0,rivalId:e['rivalId'] as String?,rivalDelta:(e['rivalDelta'] as int?)??0,requiresStat:e['requiresStat'] as String?,requiresMin:(e['requiresMin'] as int?)??0,line:e['line'] as String? ?? ''));sync();page=0;session.persist(page:page);});}
GameSnapshot snapshot()=>session.snapshot(page:page);
void restore(GameSnapshot s){setState((){session.world.restore(s);sync();page=s.page;});}
void select(int i){setState((){selected=i;session.world.progress[0]!.selected=i;session.persist();});}
Future<void> importSave()async{final c=TextEditingController();final raw=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('저장 코드 붙여넣기'),content:TextField(controller:c,maxLines:5),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('취소')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('복원'))]));if(raw==null||raw.isEmpty)return;try{restore(GameSnapshot.decode(raw));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('저장 코드가 올바르지 않습니다.')));}}
void restart(){session.save.clear();setState((){session=GameSession(JsonStoryAdapter(widget.story),createSaveAdapter());week=1;coins=12;fatigue=0;selected=0;page=0;eventIndex=0;finished=false;lastResult='';lastLine='';history.clear();stats..updateAll((k,v)=>k=='지혜'?4:k=='공감'?5:3);bonds..updateAll((k,v)=>0);milestones.clear();});}
@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,home:Scaffold(backgroundColor:paper,body:SafeArea(child:GestureDetector(onTapUp:(d){final x=d.localPosition.dx,y=d.localPosition.dy;if(page==1){if(y<100&&x>590)toggleLocale();else if(y>570&&y<635&&x<720)setState((){persona=(x~/245).clamp(0,2);session.world.progress[0]!.persona=persona;});else if(y>570)setState(()=>page=0);else if(y>180&&y<290)setState((){persona=(x~/245).clamp(0,2);session.world.progress[0]!.persona=persona;});}else if(page==2){if(y>400&&y<500)restart();}else if(page==3){if(y>260&&y<470)chooseEvent((x~/380).clamp(0,1));}else if(page==4){if(y>390&&y<470&&x<365){Clipboard.setData(ClipboardData(text:snapshot().encode()));session.persist(page:page);}else if(y>390&&y<470)importSave();else if(y>520&&x<200)setState(()=>page=0);else if(y<100)setState(()=>page=0);}else if(y>500&&x>=590)next();else if(y>500&&x>=430)setState(()=>page=1);else if(y>500&&x>=260)setState(()=>page=4);else if(y>260&&y<470){final row=y<350?0:1,col=(x~/245).clamp(0,2),i=row==0?col:3+col;if(i<activities.length)select(i);}else if(y>500)next();},child:CustomPaint(key:ValueKey('$page-$week-$persona-$eventIndex${locale=='ko'?'':'-$locale'}'),painter:Scene(widget.story,week,coins,fatigue,selected,stats,bonds,milestones,lastResult,lastLine,page,persona,image,personaImage,history,eventIndex,snapshot().encode(),activities,collectionEntries),size:const Size(760,700))))));}
class Scene extends CustomPainter{Scene(this.s,this.week,this.coins,this.fatigue,this.selected,this.stats,this.bonds,this.milestones,this.lastResult,this.lastLine,this.page,this.persona,this.image,this.personaImage,this.history,this.eventIndex,this.saveCode,this.activities,this.collectionEntries);final Map<String,dynamic>s;final int week,coins,fatigue,selected,page,persona,eventIndex;final Map<String,int>stats,bonds;final Map<String,bool>milestones;final String lastResult,lastLine;final ui.Image? image,personaImage;final List<String>history;final String saveCode;final List<Activity>activities;final List<Map<String,dynamic>>collectionEntries;void txt(Canvas c,String v,Offset p,double z,Color color,{bool bold=false}){final t=TextPainter(text:TextSpan(text:v,style:TextStyle(fontFamily:'NotoSansKR',fontSize:z,color:color,fontWeight:bold?FontWeight.w800:FontWeight.w400)),textDirection:TextDirection.ltr)..layout(maxWidth:330);t.paint(c,p);}
void box(Canvas c,Rect r,Color color,{double radius=18,Color? stroke}){c.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(radius)),Paint()..color=color);if(stroke!=null)c.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(radius)),Paint()..color=stroke..style=PaintingStyle.stroke..strokeWidth=2);}
void mark(Canvas c,String icon,Offset o,Color color){final p=Paint()..color=color..style=PaintingStyle.stroke..strokeWidth=3, q=o+const Offset(18,18);if(icon=='✦'){c.drawLine(q+const Offset(-15,0),q+const Offset(15,0),p);c.drawLine(q+const Offset(0,-15),q+const Offset(0,15),p);c.drawLine(q+const Offset(-10,-10),q+const Offset(10,10),p);c.drawLine(q+const Offset(10,-10),q+const Offset(-10,10),p);}else if(icon=='❈'){c.drawCircle(q,14,p);c.drawCircle(q,5,p);for(final a in [0.0,1.57,3.14,4.71])c.drawLine(q+Offset(cos(a)*5,sin(a)*5),q+Offset(cos(a)*14,sin(a)*14),p);}else if(icon=='◈'){final path=Path()..moveTo(q.dx,q.dy-16)..lineTo(q.dx+16,q.dy)..lineTo(q.dx,q.dy+16)..lineTo(q.dx-16,q.dy)..close();c.drawPath(path,p);}else if(icon=='☾'){c.drawArc(Rect.fromCircle(center:q,radius:15),-1.0,4.6,false,p);}else{c.drawRect(Rect.fromCenter(center:q,width:25,height:25),p);}}
void portrait(Canvas c,Rect d,int n){final sheet=page==1?personaImage:image;if(sheet!=null){final w=sheet.width/3.0,h=(page==1?sheet.height:sheet.height*.78).toDouble();c.drawImageRect(sheet,Rect.fromLTWH(n*w,0,w,h),d,Paint());return;}chibi(c,d,n);}
void chibi(Canvas c,Rect d,int n){final p=Paint()..color=const Color(0xffffd9c0),cx=d.center.dx,head=Size(d.width*.66,d.height*.42);c.drawOval(Rect.fromCenter(center:Offset(cx,d.top+d.height*.25),width:head.width,height:head.height),p);p.color=const Color(0xff273452);c.drawOval(Rect.fromCenter(center:Offset(cx,d.top+d.height*.16),width:head.width*1.08,height:head.height*.6),p);p.color=sun;for(final x in [cx-d.width*.12,cx+d.width*.12])c.drawCircle(Offset(x,d.top+d.height*.25),d.width*.035,p);p.color=teal;c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(d.left+d.width*.22,d.top+d.height*.45,d.width*.56,d.height*.27),Radius.circular(20)),p);p.color=const Color(0xffa84f3c);c.drawOval(Rect.fromLTWH(d.left+d.width*.25,d.top+d.height*.67,d.width*.22,d.height*.2),p);c.drawOval(Rect.fromLTWH(d.left+d.width*.53,d.top+d.height*.67,d.width*.22,d.height*.2),p);p.color=ink;c.drawOval(Rect.fromLTWH(d.left+d.width*.28,d.bottom-d.height*.12,d.width*.18,d.height*.12),p);c.drawOval(Rect.fromLTWH(d.left+d.width*.54,d.bottom-d.height*.12,d.width*.18,d.height*.12),p);}
@override void paint(Canvas c,Size z){final u=(z.width/760).clamp(.5,1.0);c.scale(u);box(c,const Rect.fromLTWH(0,0,760,700),paper,radius:0);if(page==1){illustration(c);drawLocaleToggle(c,activeLocale,activeCatalog);drawLocalizedIllustration(c,s,persona);return;}if(page==2){ending(c);return;}if(page==3){event(c);drawLocaleToggle(c,activeLocale,activeCatalog);drawLocalizedEvent(c,s,eventIndex,stats);return;}if(page==4){savePage(c);return;}home(c);drawFeedbackBanner(c,lastResult,lastLine);seasonProgress(c);}
void seasonProgress(Canvas c){final label=week<=3?'봄':week<=6?'여름':week<=9?'가을':'겨울',progress=(week-1)/11,people=(s['personalities'] as List? ?? const []),person=people.isEmpty?null:people[persona.clamp(0,people.length-1)],chapters=(s['progression'] as List? ?? const []),chapter=chapters.cast<Map>().firstWhere((chapter)=>(chapter['weekStart'] as int)<=week&&(chapter['weekEnd'] as int)>=week,orElse:()=>{}),chapterTitle=chapter.isEmpty?'':activeLocale=='ko'?'${chapter['title']}':localized('${chapter['titleKey']}', '${chapter['title']}');txt(c,'$label · $chapterTitle · 루멘의 $week주차 · ${person?['name'] ?? '성격 미지정'}',const Offset(24,228),10,teal,bold:true);box(c,const Rect.fromLTWH(155,231,555,5),ink.withValues(alpha: .12),radius:3);box(c,Rect.fromLTWH(155,231,555*progress,5),teal,radius:3);}
void home(Canvas c){final condition=fatigue>=10?'오늘은 무리하지 말기':fatigue>=8?'조금 지쳤어요':'마음이 맑아요',rawGoals=(s['milestones'] as List? ?? const []),pending=rawGoals.where((g)=>!milestones.containsKey(g['id'])&&g['week']>=week).toList(),goal=pending.isEmpty?null:pending.first,people=(s['personalities'] as List? ?? const []),talent=people.isEmpty?null:people[persona.clamp(0,people.length-1)];txt(c,s['title'],const Offset(24,24),30,ink,bold:true);txt(c,s['setting'],const Offset(25,65),14,teal);box(c,const Rect.fromLTWH(24,105,712,120),ink,radius:22);box(c,const Rect.fromLTWH(44,125,76,76),sun,radius:18);portrait(c,const Rect.fromLTWH(45,122,74,80),persona);txt(c,'${s['hero']} · $week주차',const Offset(140,128),20,Colors.white,bold:true);txt(c,'지혜 ${stats['지혜']}   공감 ${stats['공감']}   용기 ${stats['용기']}',const Offset(140,166),14,Colors.white70);txt(c,'은화 $coins · 피로 $fatigue/12 · $condition',const Offset(140,190),14,fatigue>9?const Color(0xffff8b6b):sun);txt(c,'유대 루미 ${bonds['lumi']} · 보라 ${bonds['bora']} · 타로 ${bonds['taro']}',const Offset(140,208),10,Colors.white70);txt(c,goal==null?'계절 목표를 모두 확인했습니다.':'다음 목표 · ${goal['title']} · ${goal['stat']} ${stats[goal['stat']]}/${goal['min']}',const Offset(24,250),14,teal,bold:true);for(var i=0;i<activities.length;i++){final a=activities[i],row=i<3?0:1,col=i<3?i:i-3,x=24+col*236.0,y=row==0?275.0:370.0,on=i==selected,bonus=talent?['focusStat']==a.stat&&a.delta>0?' · 재능 +${talent['focusBonus']}':'';box(c,Rect.fromLTWH(x,y,220,80),on?teal:Colors.white,stroke:on?teal:ink.withValues(alpha: .12));mark(c,a.icon,Offset(x+16,y+8),on?Colors.white:teal);txt(c,a.label,Offset(x+52,y+12),14,on?Colors.white:ink,bold:true);txt(c,'${a.hint}$bonus',Offset(x+52,y+40),9,on?Colors.white70:ink.withValues(alpha: .55));}txt(c,lastResult.isEmpty?'일정을 고르고 하루를 보냅니다.':lastResult,const Offset(24,470),13,lastResult.isEmpty?ink.withValues(alpha: .55):teal,bold:lastResult.isNotEmpty);box(c,const Rect.fromLTWH(260,500,150,54),Colors.white,radius:15,stroke:teal);txt(c,'기록 보관소',const Offset(282,517),14,teal,bold:true);box(c,const Rect.fromLTWH(430,500,150,54),Colors.white,radius:15,stroke:teal);txt(c,'일러스트',const Offset(458,517),16,teal,bold:true);box(c,const Rect.fromLTWH(590,500,146,54),teal,radius:15);txt(c,'하루 보내기 →',const Offset(607,517),14,Colors.white,bold:true);}
void illustration(Canvas c){final cs=(s['companions'] as List? ?? const []),p=s['personalities'][persona],comp=cs.isEmpty?null:cs[persona] as Map,talent=p['focusStat']==null?'성격의 재능은 오늘의 선택에 스며듭니다.':'재능 · ${p['focusStat']} 활동 성장 +${p['focusBonus']}';txt(c,'노아의 기록',const Offset(24,24),30,ink,bold:true);txt(c,'성격을 고르고, 오늘의 마음을 읽습니다.',const Offset(25,65),14,teal);box(c,const Rect.fromLTWH(24,100,330,455),ink,radius:24);portrait(c,const Rect.fromLTWH(46,125,286,390),(comp?['portraitFrame'] as int?)??persona);txt(c,p['name'],const Offset(390,125),24,ink,bold:true);txt(c,comp==null?p['voice']:'${comp['name']} · ${comp['role']}',const Offset(390,165),14,teal);txt(c,talent,const Offset(390,195),13,teal);box(c,const Rect.fromLTWH(390,220,330,150),Colors.white,radius:20,stroke:ink.withValues(alpha: .12));txt(c,'“${p['line']}”',const Offset(415,250),20,ink,bold:true);txt(c,'${s['hero']}의 이번 주 기록',const Offset(390,400),14,ink.withValues(alpha: .55));for(var i=0;i<3;i++){final x=24+i*236.0,on=i==persona,label=cs.isEmpty?s['personalities'][i]['name']:cs[i]['name'];box(c,Rect.fromLTWH(x,575,220,54),on?teal:Colors.white,radius:15,stroke:teal);txt(c,label,Offset(x+25,593),13,on?Colors.white:teal,bold:true);}txt(c,'← 돌아가기',const Offset(610,650),14,teal,bold:true);}
void event(Canvas c){final e=s['events'][eventIndex];txt(c,'작은 사건 · ${e['week']}주차',const Offset(24,28),30,ink,bold:true);txt(c,e['title'],const Offset(25,72),18,teal);box(c,const Rect.fromLTWH(24,120,712,110),ink,radius:22);txt(c,e['body'],const Offset(48,158),22,Colors.white,bold:true);for(var i=0;i<2;i++){final x=24+i*356.0,ch=e['choices'][i],req=ch['requiresStat'] as String?,min=ch['requiresMin'] as int?,locked=req!=null&&(stats[req]??0)<(min??0),tone=locked?paper:Colors.white,rival=ch['rivalId'] as String?,rivalDelta=(ch['rivalDelta'] as int?)??0,relation=rival==null?'':' · $rival 유대 ${rivalDelta>=0?'+':''}$rivalDelta';box(c,Rect.fromLTWH(x,270,332,190),tone,radius:18,stroke:locked?ink.withValues(alpha: .2):teal);txt(c,'선택 ${i+1}',Offset(x+22,295),14,locked?ink.withValues(alpha: .45):teal,bold:true);txt(c,ch['label'],Offset(x+22,340),19,locked?ink.withValues(alpha: .45):ink,bold:true);txt(c,locked?'조건: $req $min 필요':'${ch['stat']} +${ch['delta']}   은화 ${ch['coins']}   유대 +${(ch['bondDelta'] as int?)??0}$relation',Offset(x+22,400),13,locked?ink.withValues(alpha: .45):ink.withValues(alpha: .6));}txt(c,lastResult.startsWith('조건')?lastResult:'하나를 골라 이야기를 이어갑니다.',const Offset(24,570),14,lastResult.startsWith('조건')?const Color(0xffa84f3c):ink.withValues(alpha: .55));}
void savePage(Canvas c){final recent=history.reversed.take(3).toList(),endings=(s['endings'] as List? ?? const []).cast<Map>(),known=endings.length,discovered=collectionEntries.map((entry){final e=endings.firstWhere((candidate)=>candidate['id']==entry['id'],orElse:()=>{'title':entry['id']});return '${e['title']} ★${entry['rank']}';}).join(' · ');txt(c,'기록 보관소',const Offset(24,28),32,ink,bold:true);txt(c,'현재 상태를 코드로 보관하고 다른 실행에서 복원합니다.',const Offset(25,70),14,teal);box(c,const Rect.fromLTWH(24,120,712,240),Colors.white,radius:20,stroke:ink.withValues(alpha: .12));txt(c,'replay ${history.length}회 · 목표 ${milestones.values.where((v)=>v).length}/${(s['milestones'] as List? ?? const []).length}',const Offset(48,155),15,ink);txt(c,'유대 루미 ${bonds['lumi']} · 보라 ${bonds['bora']} · 타로 ${bonds['taro']}',const Offset(48,180),13,teal);for(var i=0;i<recent.length;i++)txt(c,recent[i].replaceAll('|line:', ' · '),Offset(48,210+i*20),10,ink.withValues(alpha: .65));txt(c,saveCode.substring(0,saveCode.length>90?90:saveCode.length),const Offset(48,285),10,ink.withValues(alpha: .45));txt(c,'엔딩 도감 ${collectionEntries.length}/$known · ${discovered.isEmpty ? '아직 발견한 결말이 없습니다.' : discovered}',const Offset(48,330),11,teal);box(c,const Rect.fromLTWH(24,390,300,64),teal,radius:18);txt(c,'저장 코드 복사',const Offset(100,412),16,Colors.white,bold:true);box(c,const Rect.fromLTWH(365,390,300,64),sun,radius:18);txt(c,'저장 코드 복원',const Offset(440,412),16,ink,bold:true);txt(c,'← 홈으로',const Offset(24,570),14,teal,bold:true);}
void ending(Canvas c){final d=resolveEnding(JsonStoryAdapter(s),stats,bonds:bonds,milestones:milestones),rank=(d['rank'] as int?)??1;txt(c,'${JsonStoryAdapter(s).endingWeek}주의 끝',const Offset(24,28),32,ink,bold:true);txt(c,'루멘은 노아가 고른 방향을 기억합니다.',const Offset(25,70),14,teal);box(c,const Rect.fromLTWH(24,110,290,420),ink,radius:24);portrait(c,const Rect.fromLTWH(55,145,228,330),persona);txt(c,d['title'],const Offset(365,145),26,ink,bold:true);txt(c,d['body'],const Offset(365,200),16,ink);txt(c,'지혜 ${stats['지혜']}   공감 ${stats['공감']}   용기 ${stats['용기']}',const Offset(365,285),15,teal);txt(c,'은화 $coins · 피로 $fatigue · 목표 ${milestones.values.where((v)=>v).length}/${(s['milestones'] as List? ?? const []).length} · 유대 ${bonds.values.reduce((a,b)=>a+b)}',const Offset(365,320),15,ink);txt(c,'루멘 기록 등급 · ${List.filled(rank, '★').join()}',const Offset(365,350),15,teal,bold:true);if(d['epilogue']!=null)txt(c,d['epilogue'],const Offset(365,378),12,teal);box(c,const Rect.fromLTWH(365,410,300,64),sun,radius:18);txt(c,'다시 루멘으로',const Offset(450,432),17,ink,bold:true);drawLocalizedEnding(c,s,d,rank);}
@override bool shouldRepaint(Scene o)=>o.week!=week||o.selected!=selected||o.page!=page||o.persona!=persona||o.image!=image||o.eventIndex!=eventIndex||o.history.length!=history.length||o.saveCode!=saveCode||o.lastResult!=lastResult||o.lastLine!=lastLine||o.bonds.toString()!=bonds.toString()||o.collectionEntries.toString()!=collectionEntries.toString();}
