import 'dart:convert';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'design_tokens.dart';
import 'save_state.dart';
import 'game_core.dart';
typedef Activity=({String label,String icon,String hint,String stat,int delta,int fatigue});
const activities=<Activity>[(label:'별 관측',icon:'✦',hint:'지혜 +3 · 피로 +1',stat:'지혜',delta:3,fatigue:1),(label:'정원 돌보기',icon:'❈',hint:'공감 +3 · 피로 +1',stat:'공감',delta:3,fatigue:1),(label:'공방 돕기',icon:'◈',hint:'용기 +2 · 은화 +4',stat:'용기',delta:2,fatigue:1)];
Future<void> main()async{WidgetsFlutterBinding.ensureInitialized();final s=jsonDecode(await rootBundle.loadString('story/story.json'));runApp(Game(s));}
class Game extends StatefulWidget{const Game(this.story,{super.key});final Map<String,dynamic>story;@override State<Game> createState()=>_Game();}
class _Game extends State<Game>{int week=1,coins=12,fatigue=0,selected=0,page=0,persona=0,eventIndex=0;bool finished=false;final history=<String>[];final stats={'지혜':4,'공감':5,'용기':3};ui.Image? image;late GameSession session;
@override void initState(){super.initState();session=GameSession(JsonStoryAdapter(widget.story),MemorySaveAdapter());rootBundle.load('assets/noa-sprite-sheet.png').then((b)=>ui.instantiateImageCodec(b.buffer.asUint8List())).then((c)=>c.getNextFrame()).then((f){if(mounted)setState(()=>image=f.image);});}
void sync(){final s=session.snapshot(page:page);week=s.week;coins=s.coins;fatigue=s.fatigue;selected=s.selected;persona=s.persona;eventIndex=s.eventIndex;history..clear()..addAll(s.history);stats..clear()..addAll(s.stats);}
void next(){final a=activities[selected];setState((){session.choose(ActivityChosen(a.stat,a.delta,selected==2?4:0,a.fatigue));sync();if(week>=12){finished=true;page=2;}else if(week%4==0&&session.story.events.isNotEmpty){eventIndex=week~/4-1;session.world.progress[0]!.eventIndex=eventIndex;page=3;}});}
void chooseEvent(int i){final e=session.story.events[eventIndex]['choices'][i],d=e['delta'] as int,g=e['coins'] as int;setState((){session.chooseEvent(StoryChoiceMade(e['stat'],d,g,e['label']));sync();page=0;});}
GameSnapshot snapshot()=>session.snapshot(page:page);
void restore(GameSnapshot s){setState((){session.world.restore(s);sync();page=s.page;});}
void select(int i){setState((){selected=i;session.world.progress[0]!.selected=i;});}
Future<void> importSave()async{final c=TextEditingController();final raw=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('저장 코드 붙여넣기'),content:TextField(controller:c,maxLines:5),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('취소')),FilledButton(onPressed:()=>Navigator.pop(context,c.text),child:const Text('복원'))]));if(raw==null||raw.isEmpty)return;try{restore(GameSnapshot.decode(raw));}catch(_){if(mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('저장 코드가 올바르지 않습니다.')));}}
void restart(){setState((){session=GameSession(JsonStoryAdapter(widget.story),MemorySaveAdapter());week=1;coins=12;selected=0;page=0;eventIndex=0;finished=false;history.clear();stats..updateAll((k,v)=>k=='지혜'?4:k=='공감'?5:3);});}
@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,home:Scaffold(backgroundColor:paper,body:SafeArea(child:GestureDetector(onTapUp:(d){final x=d.localPosition.dx,y=d.localPosition.dy;if(page==1){if(y>570)setState(()=>page=0);else if(y>180&&y<290)setState((){persona=(x~/245).clamp(0,2);session.world.progress[0]!.persona=persona;});}else if(page==2){if(y>500)restart();}else if(page==3){if(y>260&&y<470)chooseEvent((x~/380).clamp(0,1));}else if(page==4){if(y>520&&x<380){Clipboard.setData(ClipboardData(text:snapshot().encode()));session.persist(page:page);}else if(y>520)importSave();else if(y<100)setState(()=>page=0);}else if(y>500&&x>470)setState(()=>page=1);else if(y>500&&x>=300)setState(()=>page=4);else if(y>250&&y<470)select((x~/245).clamp(0,2));else if(y>500)next();},child:CustomPaint(key:ValueKey('$page-$week-$persona-$eventIndex'),painter:Scene(widget.story,week,coins,fatigue,selected,stats,page,persona,image,history,eventIndex,snapshot().encode()),size:const Size(760,700))))));}
class Scene extends CustomPainter{Scene(this.s,this.week,this.coins,this.fatigue,this.selected,this.stats,this.page,this.persona,this.image,this.history,this.eventIndex,this.saveCode);final Map<String,dynamic>s;final int week,coins,fatigue,selected,page,persona,eventIndex;final Map<String,int>stats;final ui.Image? image;final List<String>history;final String saveCode;void txt(Canvas c,String v,Offset p,double z,Color color,{bool bold=false}){final t=TextPainter(text:TextSpan(text:v,style:TextStyle(fontFamily:'Roboto',fontSize:z,color:color,fontWeight:bold?FontWeight.w800:FontWeight.w400)),textDirection:TextDirection.ltr)..layout(maxWidth:330);t.paint(c,p);}
void box(Canvas c,Rect r,Color color,{double radius=18,Color? stroke}){c.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(radius)),Paint()..color=color);if(stroke!=null)c.drawRRect(RRect.fromRectAndRadius(r,Radius.circular(radius)),Paint()..color=stroke..style=PaintingStyle.stroke..strokeWidth=2);}
void portrait(Canvas c,Rect d,int n){if(image!=null){final w=image!.width/3;c.drawImageRect(image!,Rect.fromLTWH(n*w,0,w,image!.height*.78),d,Paint());return;}chibi(c,d,n);}
void chibi(Canvas c,Rect d,int n){final p=Paint()..color=const Color(0xffffd9c0),cx=d.center.dx,head=Size(d.width*.66,d.height*.42);c.drawOval(Rect.fromCenter(center:Offset(cx,d.top+d.height*.25),width:head.width,height:head.height),p);p.color=const Color(0xff273452);c.drawOval(Rect.fromCenter(center:Offset(cx,d.top+d.height*.16),width:head.width*1.08,height:head.height*.6),p);p.color=sun;for(final x in [cx-d.width*.12,cx+d.width*.12])c.drawCircle(Offset(x,d.top+d.height*.25),d.width*.035,p);p.color=teal;c.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(d.left+d.width*.22,d.top+d.height*.45,d.width*.56,d.height*.27),Radius.circular(20)),p);p.color=const Color(0xffa84f3c);c.drawOval(Rect.fromLTWH(d.left+d.width*.25,d.top+d.height*.67,d.width*.22,d.height*.2),p);c.drawOval(Rect.fromLTWH(d.left+d.width*.53,d.top+d.height*.67,d.width*.22,d.height*.2),p);p.color=ink;c.drawOval(Rect.fromLTWH(d.left+d.width*.28,d.bottom-d.height*.12,d.width*.18,d.height*.12),p);c.drawOval(Rect.fromLTWH(d.left+d.width*.54,d.bottom-d.height*.12,d.width*.18,d.height*.12),p);}
@override void paint(Canvas c,Size z){final u=(z.width/760).clamp(.5,1.0);c.scale(u);box(c,const Rect.fromLTWH(0,0,760,700),paper,radius:0);if(page==1){illustration(c);return;}if(page==2){ending(c);return;}if(page==3){event(c);return;}if(page==4){savePage(c);return;}home(c);}
void home(Canvas c){txt(c,s['title'],const Offset(24,24),30,ink,bold:true);txt(c,s['setting'],const Offset(25,65),14,teal);box(c,const Rect.fromLTWH(24,105,712,120),ink,radius:22);box(c,const Rect.fromLTWH(44,125,76,76),sun,radius:18);portrait(c,const Rect.fromLTWH(45,122,74,80),persona);txt(c,'${s['hero']} · $week주차',const Offset(140,128),20,Colors.white,bold:true);txt(c,'지혜 ${stats['지혜']}   공감 ${stats['공감']}   용기 ${stats['용기']}',const Offset(140,166),14,Colors.white70);txt(c,'은화 $coins · 피로 $fatigue/12',const Offset(140,190),14,fatigue>9?const Color(0xffff8b6b):sun);txt(c,'이번 주의 방향',const Offset(24,250),16,ink,bold:true);for(var i=0;i<3;i++){final a=activities[i],x=24+i*236.0,on=i==selected;box(c,Rect.fromLTWH(x,280,220,150),on?teal:Colors.white,stroke:on?teal:ink.withOpacity(.12));txt(c,a.icon,Offset(x+16,298),28,on?Colors.white:teal);txt(c,a.label,Offset(x+16,365),16,on?Colors.white:ink,bold:true);txt(c,a.hint,Offset(x+16,393),11,on?Colors.white70:ink.withOpacity(.55));}txt(c,'일정을 고르고 하루를 보냅니다.',const Offset(24,610),14,ink.withOpacity(.55));box(c,const Rect.fromLTWH(260,590,150,54),Colors.white,radius:15,stroke:teal);txt(c,'기록 보관소',const Offset(282,607),14,teal,bold:true);box(c,const Rect.fromLTWH(430,590,150,54),Colors.white,radius:15,stroke:teal);txt(c,'일러스트',const Offset(458,607),16,teal,bold:true);box(c,const Rect.fromLTWH(590,590,146,54),teal,radius:15);txt(c,'하루 보내기 →',const Offset(607,607),14,Colors.white,bold:true);}
void illustration(Canvas c){txt(c,'노아의 기록',const Offset(24,24),30,ink,bold:true);txt(c,'성격을 고르고, 오늘의 마음을 읽습니다.',const Offset(25,65),14,teal);box(c,const Rect.fromLTWH(24,100,330,455),ink,radius:24);portrait(c,const Rect.fromLTWH(46,125,286,390),persona);final p=s['personalities'][persona];txt(c,p['name'],const Offset(390,125),24,ink,bold:true);txt(c,p['voice'],const Offset(390,165),14,teal);box(c,const Rect.fromLTWH(390,220,330,150),Colors.white,radius:20,stroke:ink.withOpacity(.12));txt(c,'“${p['line']}”',const Offset(415,250),20,ink,bold:true);txt(c,'${s['hero']}의 이번 주 기록',const Offset(390,400),14,ink.withOpacity(.55));for(var i=0;i<3;i++){final x=24+i*236.0,on=i==persona;box(c,Rect.fromLTWH(x,575,220,54),on?teal:Colors.white,radius:15,stroke:teal);txt(c,s['personalities'][i]['name'],Offset(x+25,593),13,on?Colors.white:teal,bold:true);}txt(c,'← 돌아가기',const Offset(610,650),14,teal,bold:true);}
void event(Canvas c){final e=s['events'][eventIndex];txt(c,'작은 사건 · ${e['week']}주차',const Offset(24,28),30,ink,bold:true);txt(c,e['title'],const Offset(25,72),18,teal);box(c,const Rect.fromLTWH(24,120,712,110),ink,radius:22);txt(c,e['body'],const Offset(48,158),22,Colors.white,bold:true);for(var i=0;i<2;i++){final x=24+i*356.0,ch=e['choices'][i];box(c,Rect.fromLTWH(x,270,332,190),Colors.white,radius:18,stroke:teal);txt(c,'선택 ${i+1}',Offset(x+22,295),14,teal,bold:true);txt(c,ch['label'],Offset(x+22,340),19,ink,bold:true);txt(c,'${ch['stat']} +${ch['delta']}   은화 ${ch['coins']}',Offset(x+22,400),13,ink.withOpacity(.6));}txt(c,'하나를 골라 이야기를 이어갑니다.',const Offset(24,570),14,ink.withOpacity(.55));}
void savePage(Canvas c){txt(c,'기록 보관소',const Offset(24,28),32,ink,bold:true);txt(c,'현재 상태를 코드로 보관하고 다른 실행에서 복원합니다.',const Offset(25,70),14,teal);box(c,const Rect.fromLTWH(24,120,712,220),Colors.white,radius:20,stroke:ink.withOpacity(.12));txt(c,'replay ${history.length}회 · ${history.join(' > ')}',const Offset(48,155),15,ink);txt(c,saveCode.substring(0,saveCode.length>120?120:saveCode.length),const Offset(48,205),12,ink.withOpacity(.6));box(c,const Rect.fromLTWH(24,390,300,64),teal,radius:18);txt(c,'저장 코드 복사',const Offset(100,412),16,Colors.white,bold:true);box(c,const Rect.fromLTWH(365,390,300,64),sun,radius:18);txt(c,'저장 코드 복원',const Offset(440,412),16,ink,bold:true);txt(c,'← 홈으로',const Offset(24,570),14,teal,bold:true);}
void ending(Canvas c){final e=stats.entries.reduce((a,b)=>a.value>b.value?a:b),defs=(s['endings'] as List? ?? []),d=defs.cast<Map<String,dynamic>>().firstWhere((x)=>x['stat']==e.key,orElse:()=>{'title':'루멘의 다음 장','body':'아직 이름 붙지 않은 가능성이 남아 있다.'});txt(c,'12주의 끝',const Offset(24,28),32,ink,bold:true);txt(c,'루멘은 노아가 고른 방향을 기억합니다.',const Offset(25,70),14,teal);box(c,const Rect.fromLTWH(24,110,290,420),ink,radius:24);portrait(c,const Rect.fromLTWH(55,145,228,330),persona);txt(c,d['title'],const Offset(365,145),26,ink,bold:true);txt(c,d['body'],const Offset(365,200),16,ink);txt(c,'지혜 ${stats['지혜']}   공감 ${stats['공감']}   용기 ${stats['용기']}',const Offset(365,285),15,teal);txt(c,'은화 $coins · 피로 $fatigue · 기록 ${history.length}회',const Offset(365,320),15,ink);box(c,const Rect.fromLTWH(365,410,300,64),sun,radius:18);txt(c,'다시 루멘으로',const Offset(450,432),17,ink,bold:true);}
@override bool shouldRepaint(Scene o)=>o.week!=week||o.selected!=selected||o.page!=page||o.persona!=persona||o.image!=image||o.eventIndex!=eventIndex||o.history.length!=history.length||o.saveCode!=saveCode;}
