import 'dart:io';
import 'package:crypto/crypto.dart';
import 'package:prince_maker/jsonl.dart';

String hash(String path) =>
    sha256.convert(File(path).readAsBytesSync()).toString();

void main() {
  final file = File('docs/review-manifest.jsonl');
  final manifest = decodeJsonl(file.readAsStringSync());
  final entries =
      (manifest['reviewedFiles'] as List).cast<Map<String, dynamic>>();
  final known = {for (final entry in entries) entry['path'] as String: entry};
  for (final entry in entries) {
    final path = entry['path'] as String;
    entry['sha256'] = hash(path);
  }
  for (final path in [
    'tool/expand_story.dart',
    'tool/generate_engine_decision.dart',
    'tool/refresh_review_manifest.dart',
    'tool/verify_scenario_variants.dart',
    'tool/trilemma_verdict.dart',
    'test/canvas_surface_test.dart',
    'lib/canvas_scene_fingerprint.dart',
    'test/canvas_scene_fingerprint_test.dart',
    'lib/activity_catalog.dart',
    'test/activity_catalog_test.dart',
    'lib/decision_receipt.dart',
    'test/decision_receipt_test.dart',
    'test/ending_matrix_test.dart',
    'test/trilemma_verdict_test.dart',
    'test/narrative_ledger_test.dart',
    'test/narrative_ledger_golden_test.dart',
    'test/goldens/narrative-ledger.png',
    'test/goldens/narrative-ledger-en.png',
    'test/system_receipt_golden_test.dart',
    'lib/character_roster.dart',
    'lib/character_art.dart',
    'lib/character_art_painter.dart',
    'test/character_roster_test.dart',
    'test/character_roster_golden_test.dart',
    'test/character_art_test.dart',
    'test/character_art_golden_test.dart',
    'test/goldens/character-roster.png',
    'test/goldens/character-roster-en.png',
    'test/goldens/character-art-doran.png',
    'test/goldens/character-art-doran-concern.png',
    'test/goldens/character-art-doran-concern-en.png',
    'assets/lumen-character-roster.png',
    'assets/generated/character-emotions/doran.png',
    'assets/generated/character-emotions/mira.png',
    'assets/generated/character-emotions/kai.png',
    'assets/generated/character-emotions/ria.png',
    'assets/generated/character-emotions/or.png',
    'assets/generated/character-emotions/sena.png',
    'assets/generated/character-emotions/bron.png',
    'assets/generated/character-emotions/elbi.png',
    'assets/generated/character-emotions/haon.png',
    'assets/generated/character-emotions/navin.png',
    'assets/generated/character-emotions/yoonseul.png',
    'assets/generated/character-emotions/moa.png',
    'assets/generated/character-emotions/sol.png',
    'assets/generated/character-emotions/eil.png',
    'assets/generated/character-emotions/raon.png',
    'assets/generated/character-emotions/morin.png',
    'assets/generated/character-emotions/daon.png',
    'assets/generated/character-emotions/biyo.png',
    'assets/generated/character-emotions/luka.png',
    'assets/generated/character-emotions/hez.png',
    'test/goldens/character-art-daon.png',
    'lib/environment_catalog.dart',
    'lib/design_tokens.dart',
    'test/environment_catalog_test.dart',
    'test/environment_golden_test.dart',
    'test/goldens/environment-atlas.png',
    'test/goldens/environment-atlas-en.png',
    'test/goldens/system-receipt.png',
    'tool/verify_game.dart',
    'tool/verify_jsonl.dart',
    'tool/migrate_jsonl.dart',
    'tool/refresh_ssot_contract_hashes.dart',
    'lib/jsonl.dart',
    'lib/quality_score.dart',
    'test/jsonl_contract_test.dart',
    'test/quality_score_test.dart',
    'test/system_receipt_golden_test.dart',
    'docs/render-quality-contract.jsonl',
    'tool/verify_render_quality.dart',
    'tool/verify_gameplay_fun.dart',
    'tool/verify_content_depth.dart',
    'tool/verify_quality_score.dart',
    'tool/generate_event_storm.dart',
    'tool/verify_event_storm.dart',
    'test/content_depth_test.dart',
    'test/event_storm_test.dart',
    'test/player_input_contract_test.dart',
    'test/player_facing_golden_test.dart',
    'test/goldens/player-home-en.png',
    'test/goldens/player-save.png',
    'test/goldens/player-save-en.png',
    'test/chapter_golden_test.dart',
    'test/chapter_closure_golden_test.dart',
    'test/goldens/chapter-arrival.png',
    'test/goldens/chapter-blankMap.png',
    'test/goldens/chapter-commons.png',
    'test/goldens/chapter-constellation.png',
    'test/goldens/chapter-crossing.png',
    'test/goldens/chapter-fairShare.png',
    'test/goldens/chapter-farShore.png',
    'test/goldens/chapter-frost.png',
    'test/goldens/chapter-handoff.png',
    'test/goldens/chapter-horizon.png',
    'test/goldens/chapter-memoryHouse.png',
    'test/goldens/chapter-reply.png',
    'test/goldens/chapter-return.png',
    'test/goldens/chapter-returningGarden.png',
    'test/goldens/chapter-seedReturn.png',
    'test/goldens/chapter-threshold.png',
    'test/goldens/chapter-closure-arrival.png',
    'test/goldens/chapter-closure-blankMap.png',
    'test/goldens/chapter-closure-commons.png',
    'test/goldens/chapter-closure-constellation.png',
    'test/goldens/chapter-closure-crossing.png',
    'test/goldens/chapter-closure-fairShare.png',
    'test/goldens/chapter-closure-farShore.png',
    'test/goldens/chapter-closure-frost.png',
    'test/goldens/chapter-closure-handoff.png',
    'test/goldens/chapter-closure-horizon.png',
    'test/goldens/chapter-closure-memoryHouse.png',
    'test/goldens/chapter-closure-reply.png',
    'test/goldens/chapter-closure-return.png',
    'test/goldens/chapter-closure-returningGarden.png',
    'test/goldens/chapter-closure-seedReturn.png',
    'test/goldens/chapter-closure-threshold.png',
    'docs/development-goals.jsonl',
    'docs/development-goals.md',
    'tool/generate_development_goals.dart',
    'tool/verify_development_goals.dart',
    'lib/decision_proof.dart',
    'docs/decision-proof-contract.jsonl',
    'tool/verify_decision_proof.dart',
    'test/decision_proof_test.dart',
    'test/relationship_dynamics_test.dart',
    'test/relationship_followup_golden_test.dart',
    'design/tokens.jsonl',
    'docs/design-system.md',
    'lib/canvas_ui_kit.dart',
    'lib/choice_impact.dart',
    'lib/canvas_choice_impact.dart',
    'test/canvas_ui_kit_test.dart',
    'test/choice_impact_test.dart',
    'test/ui_design_contract_test.dart',
    'lib/ui_state_gallery.dart',
    'test/ui_state_golden_test.dart',
    'test/goldens/ui-state-matrix.png',
    'reviews/gameplay-review.md',
    'docs/event-storm.jsonl',
    'docs/event-storm.md',
    'lib/event_art.dart',
    'test/event_art_test.dart',
    'test/event_art_golden_test.dart',
    'test/goldens/event-art.png',
    'test/goldens/event-art-en.png',
    'test/side_scene_art_test.dart',
    'test/side_scene_golden_test.dart',
    'test/engine_decision_test.dart',
    'test/personality_resonance_test.dart',
    'test/long_copy_contract_test.dart',
    'test/goldens/side-scene.png',
    'test/goldens/side-scene-en.png',
    'assets/generated/side-scene-illustrations/archive.png',
    'assets/generated/side-scene-illustrations/greenhouse.png',
    'assets/generated/side-scene-illustrations/market.png',
    'assets/generated/side-scene-illustrations/observatory.png',
    'assets/generated/side-scene-illustrations/river-road.png',
    'assets/generated/side-scene-illustrations/quarry.png',
    'tool/generate_image_matrix.dart',
    'test/image_design_matrix_test.dart',
    'design/image-design-matrix.jsonl',
    'docs/engine-decision.jsonl',
    'docs/engine-decision.md',
    ...['daon', 'biyo', 'luka', 'hez']
        .map((id) => 'assets/generated/character-emotions/$id.png'),
    ...List.generate(
        47,
        (index) =>
            'assets/generated/event-illustrations/event-${index + 2}.png'),
  ]) {
    if (!known.containsKey(path)) {
      entries
          .add({'path': path, 'ref': '$path#reviewed', 'sha256': hash(path)});
    }
  }
  file.writeAsStringSync(encodeJsonl(manifest,
      schema: 'lumen-document-jsonl-v1',
      document: 'docs/review-manifest.jsonl'));
  stdout.writeln('REVIEW_MANIFEST_REFRESHED: ${entries.length} files');
}
